pipeline:
  name: UDP Flooder Persistent
  identifier: udp_flooder_persistent
  projectIdentifier: default_project
  orgIdentifier: Sikandar
  stages:
    - stage:
        name: Run UDP Flooder
        identifier: run_udp_flooder
        type: CI
        spec:
          execution:
            steps:
              - step:
                  name: Install Dependencies
                  identifier: install_dependencies
                  type: Run
                  spec:
                    shell: bash
                    command: |
                      apt update && apt install -y python3 python3-pip tmux screen
                      pip3 install -r requirements.txt
              - step:
                  name: Start Flooder in Detached Mode
                  identifier: start_flooder
                  type: Run
                  timeout: 900s
                  spec:
                    shell: bash
                    command: |
                      tmux new-session -d -s flooder "python3 sikuser.py"
                      echo "Flooder started in tmux session"
                      sleep 800
                      echo "Flooder running in background"
