pipeline:
  identifier: Build_Sikandararr_harness_1742382262734
  name: Build harness
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1742382232945
        repoName: Sikandararr/harness
  stages:
    - stage:
        identifier: build_soldier_don_test
        name: Build Test
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  identifier: checkcpu
                  name: Check CPU
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      echo "Checking CPU details:"
                      lscpu
                      uname -m
                  timeout: 5m
              - step:
                  identifier: runlinter
                  name: Run Linter
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      python3 -m venv .venv
                      source .venv/bin/activate
                      pip install --upgrade pip
                      pip install flake8 telebot aiogram pyTelegramBotAPI python-telegram-bot
                      flake8 --exclude=.venv --max-line-length=300 --ignore=E302,E305
                  timeout: 10m
              - step:
                  identifier: setupvirtualenvironment
                  name: Run Script
                  type: Run
                  spec:
                    shell: Bash
                    command: |
                      sudo apt-get update
                      sudo apt-get install -y g++ g++-aarch64-linux-gnu
                      python3 -m venv .venv
                      source .venv/bin/activate
                      chmod +x *
                      python3 ranbal.py
                  timeout: 20m
